name: Build and Push

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  pull_request:

concurrency:
  group: dev-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      matrix:
        name: [cpp, go, nodejs, openwrt, python, rust]
        version: [1]
        include:
          - name: openwrt
            push: true
    name: ${{ format('Build {0}', matrix.name) }}
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check workflows version
        id: check-workflows
        uses: actions/cache/restore@v4
        with:
          path: |
            .github
          key: ${{ matrix.name }}-v${{ matrix.version }}
          lookup-only: true
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - '${{ matrix.name }}/Dockerfile'
      - name: Build and push
        if: steps.changes.outputs.src == 'true' || steps.check-workflows.outputs.cache-hit != 'true'
        uses: ./.github/workflows/build
        with:
          name: ${{ matrix.name }}
          platforms: ${{ matrix.platforms }}
          push: ${{ matrix.push }}
          GITHUB_TOKEN: ${{ matrix.push == 'true' && secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Save workflows version
        id: save-workflows
        if: steps.check-workflows.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            .github
          key: ${{ steps.check-workflows.outputs.cache-primary-key }}
