name: ci

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "**/base.Dockerfile"
      - ".github/workflows/*"

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: ./.github/workflows/build
        with:
          name: base
          version: 1.0.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dev:
    strategy:
      matrix:
        include:
          - name: cpp
            version: 1.0.0
          - name: nodejs
            version: 1.0.0
    runs-on: ubuntu-latest
    needs: base
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: ./.github/workflows/build
        with:
          name: ${{ matrix.name }}
          version: ${{ matrix.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
