name: ci

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "**/base.Dockerfile"

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: cpp/.devcontainer
          file: cpp/.devcontainer/base.Dockerfile
          platforms: linux/amd64
          push: ${{ github.ref_protected }}
          tags: |
            ghcr.io/slaier/dev-cpp:latest
            ghcr.io/slaier/dev-cpp:1.0.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
