name: dev

on:
  push:
    branches:
      - "main"
      - "develop"

concurrency:
  group: dev-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  dev:
    strategy:
      matrix:
        include:
          - name: cpp
            version: 1.1.0
          - name: nodejs
            version: 1.1.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: ./.github/workflows/build
        with:
          name: dev-${{ matrix.name }}
          version: ${{ matrix.version }}
          context: ${{ matrix.name }}/.devcontainer
          file: ${{ matrix.name }}/.devcontainer/base.Dockerfile
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
