name: service

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "*/Dockerfile"
      - ".github/workflows/service.yaml"
      - ".github/workflows/build/action.yaml"

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  service:
    strategy:
      matrix:
        include:
          - name: openfortivpn
            version: 1.0.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: ./.github/workflows/build
        with:
          name: ${{ matrix.name }}
          version: ${{ matrix.version }}
          context: ${{ matrix.name }}
          file: ${{ matrix.name }}/Dockerfile
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
